version: "3.7"

services:
  service_name:
    container_name: orders_service
    image: service_name:latest
    build: .
    env_file:
      - .env
    ports:
      - "3001:3001"
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app